{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "octopus-usage-exporter.fullname" . }}
  labels:
    {{- include "octopus-usage-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  API_KEY: {{ .Values.secrets.apiKey | quote }}
{{- end }}
