{{- if .Values.client.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "your-spotify.fullname" . }}-client
  labels:
    {{- include "your-spotify.client.labels" . | nindent 4 }}
  {{- with .Values.client.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.client.ingress.className }}
  ingressClassName: {{ .Values.client.ingress.className }}
  {{- end }}
  {{- if .Values.client.ingress.tls }}
  tls:
    {{- range .Values.client.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.client.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "your-spotify.fullname" $ }}-client
                port:
                  number: {{ $.Values.client.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
