apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "your-spotify.fullname" . }}-client
  labels:
    {{- include "your-spotify.client.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.client.replicaCount }}
  selector:
    matchLabels:
      {{- include "your-spotify.client.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "your-spotify.client.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.client.initContainers }}
      initContainers:
        {{- toYaml .Values.client.initContainers | nindent 8 }}
      {{- end }}
      containers:
      - name: client
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: "{{ .Values.client.image.repository }}:{{ .Values.client.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.client.image.pullPolicy }}
        {{- if .Values.client.command }}
        command:
          {{- toYaml .Values.client.command | nindent 10 }}
        {{- end }}
        {{- if .Values.client.args }}
        args:
          {{- toYaml .Values.client.args | nindent 10 }}
        {{- end }}
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        env:
        - name: API_ENDPOINT
          value: {{ .Values.config.apiEndpoint | quote }}
        {{- if .Values.client.livenessProbe }}
        livenessProbe:
          {{- toYaml .Values.client.livenessProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.client.readinessProbe }}
        readinessProbe:
          {{- toYaml .Values.client.readinessProbe | nindent 10 }}
        {{- end }}
        resources:
          {{- toYaml .Values.client.resources | nindent 10 }}
      {{- with .Values.client.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.client.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.client.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
