apiVersion: v1
kind: Service
metadata:
  name: {{ include "your-spotify.fullname" . }}-client
  labels:
    {{- include "your-spotify.client.labels" . | nindent 4 }}
spec:
  type: {{ .Values.client.service.type }}
  ports:
    - port: {{ .Values.client.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "your-spotify.client.selectorLabels" . | nindent 4 }}
