{{- if and .Values.mongodb.enabled .Values.mongodb.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "your-spotify.fullname" . }}-mongodb-pvc
  labels:
    {{- include "your-spotify.mongodb.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.mongodb.persistence.accessMode }}
  {{- if .Values.mongodb.persistence.storageClass }}
  storageClassName: {{ .Values.mongodb.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.mongodb.persistence.size }}
{{- end }}
