{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "your-spotify.fullname" . }}-mongodb
  labels:
    {{- include "your-spotify.mongodb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mongodb.service.type }}
  ports:
    - port: {{ .Values.mongodb.service.port }}
      targetPort: mongodb
      protocol: TCP
      name: mongodb
  selector:
    {{- include "your-spotify.mongodb.selectorLabels" . | nindent 4 }}
{{- end }}
