{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "your-spotify.fullname" . }}-secret
  labels:
    {{- include "your-spotify.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.spotifyPublic }}
  SPOTIFY_PUBLIC: {{ .Values.secrets.spotifyPublic | b64enc | quote }}
  {{- else }}
  SPOTIFY_PUBLIC: ""
  {{- end }}
  {{- if .Values.secrets.spotifySecret }}
  SPOTIFY_SECRET: {{ .Values.secrets.spotifySecret | b64enc | quote }}
  {{- else }}
  SPOTIFY_SECRET: ""
  {{- end }}
  {{- if .Values.secrets.keycloakUrl }}
  KEYCLOAK_URL: {{ .Values.secrets.keycloakUrl | b64enc | quote }}
  {{- else }}
  KEYCLOAK_URL: ""
  {{- end }}
  {{- if .Values.secrets.keycloakRealm }}
  KEYCLOAK_REALM: {{ .Values.secrets.keycloakRealm | b64enc | quote }}
  {{- else }}
  KEYCLOAK_REALM: ""
  {{- end }}
  {{- if .Values.secrets.keycloakClientId }}
  KEYCLOAK_CLIENT_ID: {{ .Values.secrets.keycloakClientId | b64enc | quote }}
  {{- else }}
  KEYCLOAK_CLIENT_ID: ""
  {{- end }}
  {{- if .Values.secrets.keycloakClientSecret }}
  KEYCLOAK_CLIENT_SECRET: {{ .Values.secrets.keycloakClientSecret | b64enc | quote }}
  {{- else }}
  KEYCLOAK_CLIENT_SECRET: ""
  {{- end }}
{{- end }}
