apiVersion: v2
name: your-spotify
description: A self-hosted application that tracks what you listen and offers you a dashboard to explore statistics about your Spotify usage

type: application

version: 1.0.1

appVersion: "1.11.0"

home: https://github.com/Yooooomi/your_spotify
sources:
  - https://github.com/Yooooomi/your_spotify
keywords:
  - spotify
  - statistics
  - music
  - tracking
  - dashboard
