apiVersion: v1
kind: Secret
metadata:
  name: {{ include "discord-alertmanager.fullname" . }}
  labels:
    {{- include "discord-alertmanager.labels" . | nindent 4 }}
type: Opaque
stringData:
  DISCORD_BOT_TOKEN: {{ .Values.secrets.discordBotToken | required "secrets.discordBotToken is required" | quote }}
  {{- if .Values.secrets.alertmanagerUser }}
  ALERTMANAGER_USER: {{ .Values.secrets.alertmanagerUser | quote }}
  {{- end }}
  {{- if .Values.secrets.alertmanagerPassword }}
  ALERTMANAGER_PASSWORD: {{ .Values.secrets.alertmanagerPassword | quote }}
  {{- end }}
